
name: 'Mirror GitHub Issues'

inputs:
  github-token:
    required: true
  source-repo:
    required: true
  target-repo:
    required: true
  default-close-comment:
    required: false

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: python -m pip install requests
      shell: bash

    - name: Run main.py
      run: python "${{ github.action_path }}/main.py"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SOURCE_REPO: ${{ inputs.source-repo }}
        TARGET_REPO: ${{ inputs.target-repo }}
        DEFAULT_CLOSE_COMMENT: ${{ inputs.default-close-comment }}
