name: Auto Changelog 

inputs:
  repo:
    required: true
  commit_message:
    required: true
  sections:
    required: true
  file:
    required: true
  token:
    required: true
  title:
    required: true

outputs:
  version:
    value: ${{ steps.set-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Generate Changelog
      id: set-version
      shell: pwsh
      env:
        REPO: ${{ github.repository }}
      run: |
        # Repo A (Source Repo URL) where the action is running
        $sourceRepoUrl = "https://github.com/${{ github.repository }}"

        # Repo B (Target Repo URL) where the changelog will be committed
        $targetRepoUrl = "https://github.com/${{ inputs.repo }}"

        # Input variables
        $commitMessagePattern = "${{ inputs.commit_message }}"
        $sectionsInput = "${{ inputs.sections }}"
        $filePath = "${{ inputs.file }}"
        $versionTitle = "${{ inputs.title }}"
        
        # Parse sections input
        $sections = @{}
        $sectionsInput -split "`n" | ForEach-Object {
          $sectionParts = $_.Trim() -split ":", 2
          if ($sectionParts.Count -eq 2) {
            $sections[$sectionParts[0].Trim()] = $sectionParts[1].Trim()
          } else {
            Write-Error "Invalid section format: $($_)"
            exit 1
          }
        }

        # Check for missing section headings and raise a warning
        foreach ($keyword in $sections.Keys) {
          if (-not $sections[$keyword]) {
            Write-Warning "No section heading provided for keyword '$keyword'."
            exit 1
          }
        }

        # Fetch commit history from Repo A
        Write-Host "Fetching commit history from source repository ($sourceRepoUrl)..."
        $log = git log --pretty=format:"%H|%s"
        $commits = $log -split "`n" | ForEach-Object {
          $parts = $_ -split "\|", 2
          [PSCustomObject]@{ Hash = $parts[0]; Message = $parts[1] }
        }

        # Search for version bump commits
        $pattern = [regex]::Escape($commitMessagePattern) + '\d+\.\d+(?:\.\d+)?(?:-dev)?'
        $versionBumps = $commits | Where-Object { $_.Message -match "^$pattern$" }

        if ($versionBumps.Count -eq 0) {
          Write-Warning "No version bump commit found using message '$commitMessagePattern'. Cannot generate changelog."
          exit 1
        }

        # Extract version from the latest bump
        $currentBump = $versionBumps[0]
        $versionMatch = [regex]::Match($currentBump.Message, '\d+\.\d+(?:\.\d+)?(?:-dev)?')
        $version = $versionMatch.Value

        Write-Information "Detected version bump: $version"

        echo "version=$version" >> $env:GITHUB_OUTPUT

        # Process commits for changelog generation, excluding version bump commit
        $startIndex = $commits.IndexOf($currentBump)
        $rangeCommits = $commits[($startIndex + 1)..($commits.Count - 1)]
        
        $entries = @()
        $seenMessages = @{ }

        foreach ($commit in $rangeCommits) {
          foreach ($keyword in $sections.Keys) {
            $pattern = "^$keyword\s*:\s*(.+)$"
            if ($commit.Message -match $pattern) {
              $clean = $matches[1].Trim()

              # Skip duplicate commit messages
              if ($seenMessages.ContainsKey($clean)) {
                continue
              }

              $seenMessages[$clean] = $true

              # Convert issue/PR links in commit message
              $clean = $clean -replace "PR #(\d+)", "[PR #`$1]($sourceRepoUrl/pull/`$1)"
              $clean = $clean -replace "#(\d+)", "[#`$1]($sourceRepoUrl/issues/`$1)"

              # Add commit under the corresponding section
              $entries += "- $clean"
              break
            }
          }
        }

        # Ensure the changelog has entries
        if ($entries.Count -eq 0) {
          Write-Warning "No commits found matching the defined sections and commit messages."
          exit 1
        }

        # Prepare new changelog block with the title
        $newBlock = @()
        $newBlock += $versionTitle
        $newBlock += ""
        
        # Add sections with entries under each heading
        foreach ($section in $sections.Keys) {
          $newBlock += "### $section"
          $newBlock += ""
          $newBlock += $entries -join "`n"
          $newBlock += ""
        }

        # Prepare file path and ensure directory exists
        $fileDir = Split-Path -Path $filePath -Parent
        if (-not (Test-Path $fileDir)) {
          Write-Information "Creating directory for changelog file: $fileDir"
          New-Item -ItemType Directory -Path $fileDir
        }

        # Write the changelog to the specified file
        Write-Host "Creating or updating changelog file: $filePath"
        $newBlock | Set-Content -Path $filePath -Encoding UTF8
        Write-Host "Changelog file created/updated successfully at $filePath"