name: 'Auto Changelog'
description: 'Generates a changelog from commit messages'

inputs:
  commit_message:
    description: 'Commit message pattern for version bumps (e.g., "Bump version to ")'
    required: true
  sections:
    description: 'Mapping of commit keywords to changelog section titles (e.g., "Feat: New features")'
    required: true
  file:
    description: 'Path to changelog file to write/update (e.g., Notes/change.md)'
    required: true
  token:
    description: 'GitHub token with write access to the repository'
    required: true
  title:
    description: 'Title for the changelog version block (e.g., "Version 1.2.3")'
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate Changelog
      shell: pwsh
      env:
        REPO: ${{ github.repository }}
      run: |
        $repoUrl = "https://github.com/${{ github.repository }}"
        $commitMessagePattern = "${{ inputs.commit_message }}"
        $sectionsInput = "${{ inputs.sections }}"
        $filePath = "${{ inputs.file }}"
        $versionTitle = "${{ inputs.title }}"

        if (-not $versionTitle.StartsWith("## ")) {
            $versionTitle = "## $versionTitle"
        }

        # Parse the sections (e.g., "Feat: New features")
        $sections = @{}
        $sectionsInput -split "`n" | ForEach-Object {
          $_ = $_.Trim()
          if ($_ -match "^.+:.+$") {
            $key, $value = $_ -split ":", 2
            $sections[$key.Trim()] = $value.Trim()
          }
        }

        if ($sections.Count -eq 0) {
          Write-Error "No valid sections found in input."
          exit 1
        }

        # Read commit history
        $log = git log --pretty=format:"%H|%s"
        $commits = $log -split "`n" | ForEach-Object {
          $parts = $_ -split "\|", 2
          [PSCustomObject]@{ Hash = $parts[0]; Message = $parts[1] }
        }

        # Find the most recent version bump
        $pattern = [regex]::Escape($commitMessagePattern) + '\s*\d+\.\d+(?:\.\d+)?(?:-[\w\d]+)?'
        $versionBumps = $commits | Where-Object { $_.Message -match "^$pattern$" }

        if ($versionBumps.Count -eq 0) {
          Write-Warning "No version bump commits found with pattern '$commitMessagePattern'."
          exit 1
        }

        $currentBump = $versionBumps[0]
        $versionMatch = [regex]::Match($currentBump.Message, '\d+\.\d+(?:\.\d+)?(?:-[\w\d]+)?')
        $version = $versionMatch.Value

        # Check for duplicate version in changelog file
        if (Test-Path $filePath) {
          $existingContent = Get-Content -Path $filePath -Raw
          $versionExists = $existingContent -match "(?m)^## .*\b$version\b"

          if ($versionExists) {
            Write-Warning "Changelog already contains version $version. Skipping."
            exit 0
          }
        }

        # Determine commit range for this version
        $startIndex = $commits.IndexOf($currentBump)
        $endIndex = if ($versionBumps.Count -ge 2) {
          $commits.IndexOf($versionBumps[1])
        } else {
          $commits.Count
        }

        $rangeCommits = if ($startIndex -lt $endIndex) {
          $commits[($startIndex + 1)..($endIndex - 1)]
        } else {
          $commits[($endIndex + 1)..($startIndex - 1)]
        }

        # Organize commits by section
        $entries = @{}
        $seenMessages = @{}

        foreach ($commit in $rangeCommits) {
          foreach ($keyword in $sections.Keys) {
            $pattern = "^$keyword\s*:\s*(.+)$"
            if ($commit.Message -match $pattern) {
              $clean = $matches[1].Trim()
              if (-not $seenMessages.ContainsKey($clean)) {
                $seenMessages[$clean] = $true
                $clean = $clean -replace "(?i)\bPR #(\d+)\b", "[PR #`$1]($repoUrl/pull/`$1)"
                $clean = $clean -replace "(?<!PR )#(\d+)", "[#`$1]($repoUrl/issues/`$1)"

                if (-not $entries.ContainsKey($keyword)) {
                  $entries[$keyword] = @()
                }
                $entries[$keyword] += "- $clean"
              }
              break
            }
          }
        }

        if ($entries.Count -eq 0) {
          Write-Warning "No matching commit messages found for changelog."
          exit 1
        }

        # Build the new changelog block
        $newBlock = @()
        $newBlock += $versionTitle
        $newBlock += ""

        foreach ($keyword in $sections.Keys) {
          if ($entries.ContainsKey($keyword)) {
            $newBlock += "### $($sections[$keyword])"
            $newBlock += ""
            $newBlock += $entries[$keyword]
            $newBlock += ""
          }
        }

        # Ensure directory exists
        $fileDir = Split-Path -Path $filePath -Parent
        if (-not (Test-Path $fileDir)) {
          New-Item -ItemType Directory -Path $fileDir | Out-Null
        }

        # Append to the changelog file
        Add-Content -Path $filePath -Value ($newBlock -join "`n")
        Write-Information "Changelog written to $filePath" -InformationAction Continue
