name: 'Auto Changelog'
description: 'Generates a changelog from commit messages for the current version bump'

inputs:
  commit_message:
    description: 'Commit message pattern for version bumps (e.g., "Bump version to")'
    required: true
  sections:
    description: 'Mapping of commit keywords to changelog section titles (e.g., "Feat: New features")'
    required: true
  file:
    description: 'Path to changelog file to write/update (e.g., Notes/change.md)'
    required: true
  token:
    description: 'GitHub token with write access to the repository'
    required: true
  title:
    description: 'Title for the changelog version block (e.g., "## Version 1.2.3")'
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate Changelog
      shell: pwsh
      env:
        REPO: ${{ github.repository }}
      run: |
        $repoUrl = "https://github.com/${{ github.repository }}"
        $commitMessagePattern = "${{ inputs.commit_message }}"
        $sectionsInput = "${{ inputs.sections }}"
        $filePath = "${{ inputs.file }}"
        $versionTitle = "${{ inputs.title }}"

        if (-not $versionTitle.StartsWith("## ")) {
            $versionTitle = "## $versionTitle"
        }

        # Parse sections
        $sections = @{}
        $sectionsInput -split "`n" | ForEach-Object {
            $_ = $_.Trim()
            if ($_ -and ($_ -match "^.+:.+$")) {
                $key, $value = $_ -split ":", 2
                $sections[$key.Trim()] = $value.Trim()
            }
        }

        if ($sections.Count -eq 0) {
            Write-Error "No valid sections found in input."
            exit 1
        }

        # Get commit history
        $log = git log --pretty=format:"%H|%s"
        $commits = $log -split "`n" | ForEach-Object {
            $parts = $_ -split "\|", 2
            [PSCustomObject]@{ Hash = $parts[0]; Message = $parts[1].Trim() }
        }

        # Find version bump commits
        $versionRegex = '\d+\.\d+(?:\.\d+)?(?:-[\w\d]+)?'
        $bumpPattern = [regex]::Escape($commitMessagePattern.Trim()) + '\s*' + $versionRegex + '\s*$'
        $versionBumps = $commits | Where-Object { $_.Message -match "^$bumpPattern" }

        if ($versionBumps.Count -eq 0) {
            Write-Warning "No version bump commits found matching '$commitMessagePattern'"
            exit 0
        }

        # Use the most recent version bump
        $currentBump = $versionBumps[-1]
        $version = ([regex]::Match($currentBump.Message, $versionRegex)).Value

        # Detect duplicate version bumps
        $allVersions = $commits | ForEach-Object {
            $match = [regex]::Match($_.Message, $versionRegex)
            if ($match.Success) { $match.Value } else { $null }
        } | Where-Object { $_ -eq $version }

        if ($allVersions.Count -gt 1) {
            Write-Warning "Duplicate version bump detected for version $version. Skipping changelog generation."
            exit 0
        }

        # Filter commits after the current bump
        $startIndex = $commits.IndexOf($currentBump)
        if ($startIndex -ge ($commits.Count - 1)) {
            Write-Warning "No commits found after version bump."
            exit 0
        }

        $rangeCommits = $commits[($startIndex + 1)..($commits.Count - 1)]

        # Collect and organize entries
        $entries = @{}
        $seenHashes = @{}
        foreach ($section in $sections.Keys) {
            $entries[$section] = @()
        }

        foreach ($commit in $rangeCommits) {
            if ($seenHashes.ContainsKey($commit.Hash)) { continue }
            foreach ($keyword in $sections.Keys) {
                if ($commit.Message -match "^$keyword\s*:\s*(.+)$") {
                    $msg = $matches[1].Trim()
                    if ($msg) {
                        # Fix PR link regex
                        $msg = $msg -replace "(?i)\bPR #(\d+)\b", "[PR #$1]($repoUrl/pull/$1)"
                        $msg = $msg -replace "(?<!\\[)#(\d+)", "[#$1]($repoUrl/issues/$1)"
                        $entries[$keyword] += "- $msg"
                        $seenHashes[$commit.Hash] = $true
                    }
                    break
                }
            }
        }

        $totalEntries = ($entries.Values | ForEach-Object { $_.Count } | Measure-Object -Sum).Sum
        if ($totalEntries -eq 0) {
            Write-Warning "No changelog entries matched section keywords after version bump."
            exit 0
        }

        # Build changelog block
        $block = @()
        $block += $versionTitle
        $block += ""

        foreach ($keyword in $sections.Keys) {
            if ($entries[$keyword].Count -gt 0) {
                $block += "### $($sections[$keyword])"
                $block += ""
                $block += $entries[$keyword]
                $block += ""
            }
        }

        # Ensure changelog directory exists
        $dir = Split-Path -Parent $filePath
        if (-not (Test-Path $dir)) {
            New-Item -ItemType Directory -Path $dir -Force | Out-Null
        }

        # Append changelog
        Add-Content -Path $filePath -Value ($block -join "`n")
        Write-Information "Changelog updated in $filePath" -InformationAction Continue
