name: 'Auto Changelog'
description: 'Generates a changelog from commit messages'

inputs:
  commit_message:
    description: 'Commit message pattern for version bumps (e.g., "Bump version to")'
    required: true
  sections:
    description: 'Mapping of commit keywords to changelog section titles (e.g., "Feat: New features")'
    required: true
  file:
    description: 'Path to changelog file to write/update (e.g., Notes/change.md)'
    required: true
  token:
    description: 'GitHub token with write access to the repository'
    required: true
  title:
    description: 'Title for the changelog version block (e.g., "## Version 1.2.3")'
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate Changelog
      shell: pwsh
      env:
        REPO: ${{ github.repository }}
      run: |
        $repoUrl = "https://github.com/${{ github.repository }}"
        $commitMessagePattern = "${{ inputs.commit_message }}"
        $sectionsInput = "${{ inputs.sections }}"
        $filePath = "${{ inputs.file }}"
        $versionTitle = "${{ inputs.title }}"

        # Ensure title starts with '## '
        if (-not $versionTitle.StartsWith("## ")) {
            $versionTitle = "## $versionTitle"
        }

        # Parse section mappings
        $sections = @{}
        $sectionsInput -split "`n" | ForEach-Object {
          $_ = $_.Trim()
          if ($_ -and ($_ -match "^.+:.+$")) {
            $key, $value = $_ -split ":", 2
            $sections[$key.Trim()] = $value.Trim()
          }
        }

        if ($sections.Count -eq 0) {
          Write-Error "No valid sections found in input."
          exit 1
        }

        # Get commit history
        $log = git log --pretty=format:"%H|%s"
        $commits = $log -split "`n" | ForEach-Object {
          $parts = $_ -split "\|", 2
          [PSCustomObject]@{ Hash = $parts[0]; Message = $parts[1] }
        }

        # Find all version bump commits
        $pattern = [regex]::Escape($commitMessagePattern) + '\s*\d+\.\d+(?:\.\d+)?(?:-[\w\d]+)?'
        $versionBumps = $commits | Where-Object { $_.Message -match "^$pattern$" }

        if ($versionBumps.Count -eq 0) {
          Write-Warning "No version bump commits found matching '$commitMessagePattern'"
          exit 1
        }

        # Extract current version
        $currentBump = $versionBumps[0]
        $versionMatch = [regex]::Match($currentBump.Message, '\d+\.\d+(?:\.\d+)?(?:-[\w\d]+)?')
        $version = $versionMatch.Value

        # Check for duplicate version bumps in commit history
        $versionDuplicates = $commits | Where-Object {
          $_.Message -eq "$commitMessagePattern $version"
        }

        if ($versionDuplicates.Count -gt 1) {
          Write-Warning "Duplicate version bump detected for version $version. Skipping changelog generation."
          exit 0
        }

        # Determine commit range
        $startIndex = $commits.IndexOf($currentBump)
        $endIndex = if ($versionBumps.Count -ge 2) {
          $commits.IndexOf($versionBumps[1])
        } else {
          $commits.Count
        }

        $rangeCommits = if ($startIndex -lt $endIndex) {
          $commits[($startIndex + 1)..($endIndex - 1)]
        } else {
          $commits[($endIndex + 1)..($startIndex - 1)]
        }

        # Initialize entries
        $entries = @{}
        foreach ($section in $sections.Keys) {
          $entries[$section] = @()
        }
        $seen = @{}

        # Parse matching commits
        foreach ($commit in $rangeCommits) {
          foreach ($keyword in $sections.Keys) {
            if ($commit.Message -match "^$keyword\s*:\s*(.+)$") {
              $msg = $matches[1].Trim()
              if (-not $seen.ContainsKey($msg)) {
                $seen[$msg] = $true
                $msg = $msg -replace "(?i)\bPR #(\d+)\b", "[PR #$1]($repoUrl/pull/$1)"
                $msg = $msg -replace "(?<!PR )#(\d+)", "[#$1]($repoUrl/issues/$1)"
                $entries[$keyword] += "- $msg"
              }
              break
            }
          }
        }

        if (($entries.Values | ForEach-Object { $_.Count } | Measure-Object -Sum).Sum -eq 0) {
          Write-Warning "No matching commit messages found for changelog."
          exit 1
        }

        # Prepare changelog block
        $block = @()
        $block += $versionTitle
        $block += ""

        foreach ($keyword in $sections.Keys) {
          if ($entries[$keyword].Count -gt 0) {
            $block += "### $($sections[$keyword])"
            $block += ""
            $block += $entries[$keyword]
            $block += ""
          }
        }

        # Ensure changelog directory exists
        $dir = Split-Path -Parent $filePath
        if (-not (Test-Path $dir)) {
          New-Item -ItemType Directory -Path $dir -Force | Out-Null
        }

        # Append changelog block
        Add-Content -Path $filePath -Value ($block -join "`n")
        Write-Information "Changelog updated in $filePath" -InformationAction Continue
