name: Push-Devlog

inputs:
  keywords:
    required: true
  section:
    required: false
  file:
    required: true

outputs:
  version:
    value: ${{ steps.set-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Generate Devlog
      id: set-version
      shell: pwsh
      env:
        REPO: ${{ github.repository }}
      run: |
        $repo = $env:REPO
        $repoUrl = "https://github.com/$repo"

        $keywordsInput = "${{ inputs.keywords }}"
        $sectionInput = "${{ inputs.section }}"
        $fileName = "${{ inputs.file }}"

        $keywords = $keywordsInput -split "`n" | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" }
        $sectionMap = @{}

        if ($sectionInput -ne "") {
            Write-Host "Custom section mapping detected."
            foreach ($line in $sectionInput -split "`n") {
                if ($line -match "^(.*?):(.*)$") {
                    $sectionMap[$matches[1].Trim()] = $matches[2].Trim()
                }
            }
        }

        $hasSections = $sectionMap.Count -gt 0
        $entries = @()
        $sections = @{}
        $seenMessages = @{}

        Write-Host "Fetching commit history..."
        $log = git log --pretty=format:"%H|%s"
        $commits = $log -split "`n" | ForEach-Object {
            $parts = $_ -split "\|", 2
            [PSCustomObject]@{ Hash = $parts[0]; Message = $parts[1] }
        }

        Write-Host "Searching for version bump commits..."
        $versionBumps = $commits | Where-Object {
            $_.Message -match '^Bump version to \d+\.\d+(?:\.\d+)?(?:-dev)?$'
        }

        if ($versionBumps.Count -eq 0) {
            Write-Warning "No version bump commit found. Cannot generate Devlog."
            exit 1
        }

        $currentBump = $versionBumps[0]
        $versionMatch = [regex]::Match($currentBump.Message, '\d+\.\d+(?:\.\d+)?(?:-dev)?')
        $version = $versionMatch.Value

        # Check for duplicate version bump earlier in history
        $duplicate = $versionBumps | Where-Object {
            $_.Message -eq "Bump version to $version" -and $_.Hash -ne $currentBump.Hash
        }

        if ($duplicate.Count -gt 0) {
            Write-Warning "Duplicate version bump found for version $version. Skipping Devlog generation."
            exit 0
        }

        Write-Host "Version extracted."
        echo "version=$version" >> $env:GITHUB_OUTPUT

        $startIndex = $commits.IndexOf($currentBump)
        $endIndex = if ($versionBumps.Count -ge 2) {
            $commits.IndexOf($versionBumps[1])
        } else {
            $commits.Count
        }

        $rangeCommits = $commits[($startIndex + 1) .. ($endIndex - 1)]

        foreach ($commit in $rangeCommits) {
            foreach ($keyword in $keywords) {
                $pattern = "^$keyword\s*:\s*(.+)$"
                if ($commit.Message -match $pattern) {
                    $clean = $matches[1].Trim()

                    # Skip duplicates
                    if ($seenMessages.ContainsKey($clean)) {
                        continue
                    }
                    $seenMessages[$clean] = $true

                    # Link conversion
                    $clean = $clean -replace "PR #(\d+)", "[PR #`$1]($repoUrl/pull/`$1)"
                    $clean = $clean -replace "#(\d+)", "[#`$1]($repoUrl/issues/`$1)"

                    if ($hasSections) {
                        $heading = $sectionMap[$keyword]
                        if (-not $sections.ContainsKey($heading)) {
                            $sections[$heading] = @()
                        }
                        $sections[$heading] += "- $clean"
                    } else {
                        $entries += "- $clean"
                    }
                    break
                }
            }
        }

        Write-Host "Creating Devlog file: $fileName"
        $lines = @()

        if ($hasSections) {
            foreach ($heading in $sections.Keys) {
                $lines += "## $heading"
                $lines += $sections[$heading]
                $lines += ""
            }
        } else {
            $lines += $entries
        }

        $lines | Set-Content -Path $fileName -Encoding UTF8
        Write-Host "Devlog file created successfully: $fileName"
