name: Push-Devlog

description: |
  Composite GitHub Action that generates release notes from commit messages
  and writes them to a custom markdown file based on version bump commits.

inputs:
  prefix:
    description: |
      List of commit message prefixes to include (one per line), matching the format: prefix: message.
      For example: added, fixed, improved.
    required: true

  section:
    description: |
      Optional mapping of prefix to section heading. Format: prefix:Section Heading
      For example: added:New Features, fixed:Bug Fixes.
    required: false

  file:
    description: |
      Name of the output file to write the release notes (e.g., Devlog.md).
    required: true

outputs:
  version:
    description: "Extracted version number from the version bump commit (e.g., 1.2.3 or 1.2.3-dev)."

runs:
  using: "composite"
  steps:
    - name: "Generate release notes and write to file"
      id: generate
      shell: pwsh
      run: |
        Write-Host "[INFO] Starting release notes generation..."

        $prefixInput = "${{ inputs.prefix }}"
        $sectionInput = "${{ inputs.section }}"
        $fileName = "${{ inputs.file }}"

        # Extract and prepare prefix list
        $prefixes = $prefixInput -split "`n" | ForEach-Object { $_.Trim().ToLower() } | Where-Object { $_ -ne "" }
        $sectionMap = @{}

        # Process section mappings
        if ($sectionInput -ne "") {
            Write-Host "[INFO] Creating sections..."
            foreach ($line in $sectionInput -split "`n") {
                if ($line -match "^(.*?):(.*)$") {
                    $sectionMap[$matches[1].Trim().ToLower()] = $matches[2].Trim()
                }
            }
        }

        # Get full commit history
        Write-Host "[INFO] Extracting commit history..."
        $log = git log --pretty=format:"%H|%s"
        $commits = $log -split "`n" | ForEach-Object {
            $parts = $_ -split "\|", 2
            [PSCustomObject]@{ Hash = $parts[0]; Message = $parts[1] }
        }

        # Identify all bump commits
        Write-Host "[INFO] Checking for version bumps..."
        $bumpPattern = '^Bump version to \d+\.\d+(?:\.\d+)?(?:-dev)?$'
        $versionBumps = $commits | Where-Object { $_.Message -match $bumpPattern }

        if ($versionBumps.Count -eq 0) {
            Write-Warning "[WARNING] No version bump commit found. Cannot generate Devlog."
            exit 1
        }

        $currentBump = $versionBumps[0]
        $versionMatch = [regex]::Match($currentBump.Message, '\d+\.\d+(?:\.\d+)?(?:-dev)?')
        $version = $versionMatch.Value
        echo "::set-output name=version::$version"
        Write-Host "[INFO] Found version bump: $version"

        $startIndex = $commits.IndexOf($currentBump)
        $endIndex = if ($versionBumps.Count -ge 2) {
            $commits.IndexOf($versionBumps[1])
        } else {
            $commits.Count
        }

        # Determine the commit range
        $rangeCommits = $commits[($startIndex + 1) .. ($endIndex - 1)]

        # Group commits by section
        $sections = @{}

        foreach ($commit in $rangeCommits) {
            foreach ($prefix in $prefixes) {
                if ($commit.Message.ToLower() -like "$prefix:*") {
                    $clean = $commit.Message.Substring($prefix.Length + 1).Trim()
                    if ($sectionMap.ContainsKey($prefix)) {
                        $heading = $sectionMap[$prefix]
                        if (-not $sections.ContainsKey($heading)) {
                            $sections[$heading] = @()
                        }
                        $sections[$heading] += "- $clean"
                    }
                    break
                }
            }
        }

        Write-Host "[INFO] Creating Devlog file: $fileName"
        $lines = @()
        $lines += "# Devlog - Version $version"
        $lines += ""

        if ($sections.Count -eq 0) {
            Write-Warning "[WARNING] No qualifying commits found for this version."
        } else {
            foreach ($heading in $sections.Keys) {
                $lines += "## $heading"
                $lines += $sections[$heading]
                $lines += ""
            }
        }

        $lines | Set-Content -Path $fileName -Encoding UTF8
        Write-Host "[INFO] Devlog file created successfully: $fileName"
